# Generated by Django 2.2.15 on 2020-08-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_voluneering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='info',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
        migrations.DeleteModel(
            name='voluneering',
        ),
        migrations.DeleteModel(
            name='work',
        ),
    ]
